export const COUNTRY_CODE = {
  AD: { name: '안도라', flag: 'AD' },
  AE: { name: '아랍에미리트', flag: 'AE' },
  AF: { name: '아프가니스탄', flag: 'AF' },
  AG: { name: '앤티가 바부다', flag: 'AG' },
  AI: { name: '앵귈라', flag: 'AI' },
  AL: { name: '알바니아', flag: 'AL' },
  AM: { name: '아르메니아', flag: 'AM' },
  AO: { name: '앙골라', flag: 'AO' },
  AQ: { name: '남극', flag: 'AQ' },
  AR: { name: '아르헨티나', flag: 'AR' },
  AS: { name: '아메리칸사모아', flag: 'AS' },
  AT: { name: '오스트리아', flag: 'AT' },
  AU: { name: '오스트레일리아', flag: 'AU' },
  AW: { name: '아루바', flag: 'AW' },
  AX: { name: '올란드 제도', flag: 'AX' },
  AZ: { name: '아제르바이잔', flag: 'AZ' },
  BA: { name: '보스니아 헤르체고비나', flag: 'BA' },
  BB: { name: '바베이도스', flag: 'BB' },
  BD: { name: '방글라데시', flag: 'BD' },
  BE: { name: '벨기에', flag: 'BE' },
  BF: { name: '부르키나파소', flag: 'BF' },
  BG: { name: '불가리아', flag: 'BG' },
  BH: { name: '바레인', flag: 'BH' },
  BI: { name: '부룬디', flag: 'BI' },
  BJ: { name: '베냉', flag: 'BJ' },
  BL: { name: '생바르텔레미', flag: 'BL' },
  BM: { name: '버뮤다', flag: 'BM' },
  BN: { name: '브루나이', flag: 'BN' },
  BO: { name: '볼리비아', flag: 'BO' },
  BQ: { name: '보네르섬', flag: 'BQ' },
  BR: { name: '브라질', flag: 'BR' },
  BS: { name: '바하마', flag: 'BS' },
  BT: { name: '부탄', flag: 'BT' },
  BV: { name: '부베섬', flag: 'BV' },
  BW: { name: '보츠와나', flag: 'BW' },
  BY: { name: '벨라루스', flag: 'BY' },
  BZ: { name: '벨리즈', flag: 'BZ' },
  CA: { name: '캐나다', flag: 'CA' },
  CC: { name: '코코스 제도', flag: 'CC' },
  CD: { name: '콩고 민주 공화국', flag: 'CD' },
  CF: { name: '중앙아프리카 공화국', flag: 'CF' },
  CG: { name: '콩고 공화국', flag: 'CG' },
  CH: { name: '스위스', flag: 'CH' },
  CI: { name: '코트디부아르', flag: 'CI' },
  CK: { name: '쿡 제도', flag: 'CK' },
  CL: { name: '칠레', flag: 'CL' },
  CM: { name: '카메룬', flag: 'CM' },
  CN: { name: '중국', flag: 'CN' },
  CO: { name: '콜롬비아', flag: 'CO' },
  CR: { name: '코스타리카', flag: 'CR' },
  CU: { name: '쿠바', flag: 'CU' },
  CV: { name: '카보베르데', flag: 'CV' },
  CW: { name: '퀴라소', flag: 'CW' },
  CX: { name: '크리스마스섬', flag: 'CX' },
  CY: { name: '키프로스', flag: 'CY' },
  CZ: { name: '체코', flag: 'CZ' },
  DE: { name: '독일', flag: 'DE' },
  DJ: { name: '지부티', flag: 'DJ' },
  DK: { name: '덴마크', flag: 'DK' },
  DM: { name: '도미니카 연방', flag: 'DM' },
  DO: { name: '도미니카 공화국', flag: 'DO' },
  DZ: { name: '알제리', flag: 'DZ' },
  EC: { name: '에콰도르', flag: 'EC' },
  EE: { name: '에스토니아', flag: 'EE' },
  EG: { name: '이집트', flag: 'EG' },
  EH: { name: '서사하라', flag: 'EH' },
  ER: { name: '에리트레아', flag: 'ER' },
  ES: { name: '스페인', flag: 'ES' },
  ET: { name: '에티오피아', flag: 'ET' },
  FI: { name: '핀란드', flag: 'FI' },
  FJ: { name: '피지', flag: 'FJ' },
  FK: { name: '포클랜드 제도', flag: 'FK' },
  FM: { name: '미크로네시아 연방', flag: 'FM' },
  FO: { name: '페로 제도', flag: 'FO' },
  FR: { name: '프랑스', flag: 'FR' },
  GA: { name: '가봉', flag: 'GA' },
  GB: { name: '영국', flag: 'GB' },
  GD: { name: '그레나다', flag: 'GD' },
  GE: { name: '조지아', flag: 'GE' },
  GF: { name: '프랑스령 기아나', flag: 'GF' },
  GG: { name: '건지섬', flag: 'GG' },
  GH: { name: '가나', flag: 'GH' },
  GI: { name: '지브롤터', flag: 'GI' },
  GL: { name: '그린란드', flag: 'GL' },
  GM: { name: '감비아', flag: 'GM' },
  GN: { name: '기니', flag: 'GN' },
  GP: { name: '과들루프', flag: 'GP' },
  GQ: { name: '적도 기니', flag: 'GQ' },
  GR: { name: '그리스', flag: 'GR' },
  GS: { name: '사우스조지아 사우스샌드위치 제도', flag: 'GS' },
  GT: { name: '과테말라', flag: 'GT' },
  GU: { name: '괌', flag: 'GU' },
  GW: { name: '기니비사우', flag: 'GW' },
  GY: { name: '가이아나', flag: 'GY' },
  HK: { name: '홍콩', flag: 'HK' },
  HM: { name: '허드 맥도널드 제도', flag: 'HM' },
  HN: { name: '온두라스', flag: 'HN' },
  HR: { name: '크로아티아', flag: 'HR' },
  HT: { name: '아이티', flag: 'HT' },
  HU: { name: '헝가리', flag: 'HU' },
  ID: { name: '인도네시아', flag: 'ID' },
  IE: { name: '아일랜드', flag: 'IE' },
  IL: { name: '이스라엘', flag: 'IL' },
  IM: { name: '맨섬', flag: 'IM' },
  IN: { name: '인도', flag: 'IN' },
  IO: { name: '영국령 인도양 지역', flag: 'IO' },
  IQ: { name: '이라크', flag: 'IQ' },
  IR: { name: '이란', flag: 'IR' },
  IS: { name: '아이슬란드', flag: 'IS' },
  IT: { name: '이탈리아', flag: 'IT' },
  JE: { name: '저지섬', flag: 'JE' },
  JM: { name: '자메이카', flag: 'JM' },
  JO: { name: '요르단', flag: 'JO' },
  JP: { name: '일본', flag: 'JP' },
  KE: { name: '케냐', flag: 'KE' },
  KG: { name: '키르기스스탄', flag: 'KG' },
  KH: { name: '캄보디아', flag: 'KH' },
  KI: { name: '키리바시', flag: 'KI' },
  KM: { name: '코모로', flag: 'KM' },
  KN: { name: '세인트키츠 네비스', flag: 'KN' },
  KP: { name: '조선민주주의인민공화국', flag: 'KP' },
  KR: { name: '대한민국', flag: 'KR' },
  KW: { name: '쿠웨이트', flag: 'KW' },
  KY: { name: '케이맨 제도', flag: 'KY' },
  KZ: { name: '카자흐스탄', flag: 'KZ' },
  LA: { name: '라오스', flag: 'LA' },
  LB: { name: '레바논', flag: 'LB' },
  LC: { name: '세인트루시아', flag: 'LC' },
  LK: { name: '스리랑카', flag: 'LK' },
  LI: { name: '리히텐슈타인', flag: 'LI' },
  LR: { name: '라이베리아', flag: 'LR' },
  LS: { name: '레소토', flag: 'LS' },
  LT: { name: '리투아니아', flag: 'LT' },
  LU: { name: '룩셈부르크', flag: 'LU' },
  LV: { name: '라트비아', flag: 'LV' },
  LY: { name: '리비아', flag: 'LY' },
  MA: { name: '모로코', flag: 'MA' },
  MC: { name: '모나코', flag: 'MC' },
  MD: { name: '몰도바', flag: 'MD' },
  ME: { name: '몬테네그로', flag: 'ME' },
  MF: { name: '생마르탱', flag: 'MF' },
  MG: { name: '마다가스카르', flag: 'MG' },
  MH: { name: '마셜 제도', flag: 'MH' },
  MK: { name: '북마케도니아', flag: 'MK' },
  ML: { name: '말리', flag: 'ML' },
  MM: { name: '미얀마', flag: 'MM' },
  MN: { name: '몽골', flag: 'MN' },
  MO: { name: '마카오', flag: 'MO' },
  MP: { name: '북마리아나 제도', flag: 'MP' },
  MQ: { name: '마르티니크', flag: 'MQ' },
  MR: { name: '모리타니', flag: 'MR' },
  MS: { name: '몬트세랫', flag: 'MS' },
  MT: { name: '몰타', flag: 'MT' },
  MU: { name: '모리셔스', flag: 'MU' },
  MV: { name: '몰디브', flag: 'MV' },
  MW: { name: '말라위', flag: 'MW' },
  MX: { name: '멕시코', flag: 'MX' },
  MY: { name: '말레이시아', flag: 'MY' },
  MZ: { name: '모잠비크', flag: 'MZ' },
  NA: { name: '나미비아', flag: 'NA' },
  NC: { name: '누벨칼레도니', flag: 'NC' },
  NE: { name: '니제르', flag: 'NE' },
  NF: { name: '노퍽섬', flag: 'NF' },
  NG: { name: '나이지리아', flag: 'NG' },
  NI: { name: '니카라과', flag: 'NI' },
  NL: { name: '네덜란드', flag: 'NL' },
  NO: { name: '노르웨이', flag: 'NO' },
  NP: { name: '네팔', flag: 'NP' },
  NR: { name: '나우루', flag: 'NR' },
  NU: { name: '니우에', flag: 'NU' },
  NZ: { name: '뉴질랜드', flag: 'NZ' },
  OM: { name: '오만', flag: 'OM' },
  PA: { name: '파나마', flag: 'PA' },
  PE: { name: '페루', flag: 'PE' },
  PF: { name: '프랑스령 폴리네시아', flag: 'PF' },
  PG: { name: '파푸아뉴기니', flag: 'PG' },
  PH: { name: '필리핀', flag: 'PH' },
  PK: { name: '파키스탄', flag: 'PK' },
  PL: { name: '폴란드', flag: 'PL' },
  PM: { name: '생피에르 미클롱', flag: 'PM' },
  PN: { name: '핏케언 제도', flag: 'PN' },
  PR: { name: '푸에르토리코', flag: 'PR' },
  PS: { name: '팔레스타인', flag: 'PS' },
  PT: { name: '포르투갈', flag: 'PT' },
  PW: { name: '팔라우', flag: 'PW' },
  PY: { name: '파라과이', flag: 'PY' },
  QA: { name: '카타르', flag: 'QA' },
  RE: { name: '레위니옹', flag: 'RE' },
  RO: { name: '루마니아', flag: 'RO' },
  RS: { name: '세르비아', flag: 'RS' },
  RU: { name: '러시아', flag: 'RU' },
  RW: { name: '르완다', flag: 'RW' },
  SA: { name: '사우디아라비아', flag: 'SA' },
  SB: { name: '솔로몬 제도', flag: 'SB' },
  SC: { name: '세이셸', flag: 'SC' },
  SD: { name: '수단', flag: 'SD' },
  SE: { name: '스웨덴', flag: 'SE' },
  SG: { name: '싱가포르', flag: 'SG' },
  SH: { name: '세인트헬레나', flag: 'SH' },
  SI: { name: '슬로베니아', flag: 'SI' },
  SJ: { name: '스발바르 얀마옌', flag: 'SJ' },
  SK: { name: '슬로바키아', flag: 'SK' },
  SL: { name: '시에라리온', flag: 'SL' },
  SM: { name: '산마리노', flag: 'SM' },
  SN: { name: '세네갈', flag: 'SN' },
  SO: { name: '소말리아', flag: 'SO' },
  SR: { name: '수리남', flag: 'SR' },
  SS: { name: '남수단', flag: 'SS' },
  ST: { name: '상투메 프린시페', flag: 'ST' },
  SV: { name: '엘살바도르', flag: 'SV' },
  SX: { name: '신트마르턴', flag: 'SX' },
  SY: { name: '시리아', flag: 'SY' },
  SZ: { name: '에스와티니', flag: 'SZ' },
  TC: { name: '터크스 케이커스 제도', flag: 'TC' },
  TD: { name: '차드', flag: 'TD' },
  TF: { name: '프랑스령 남방 및 남극 지역', flag: 'TF' },
  TG: { name: '토고', flag: 'TG' },
  TH: { name: '태국', flag: 'TH' },
  TJ: { name: '타지키스탄', flag: 'TJ' },
  TK: { name: '토켈라우', flag: 'TK' },
  TL: { name: '동티모르', flag: 'TL' },
  TM: { name: '투르크메니스탄', flag: 'TM' },
  TN: { name: '튀니지', flag: 'TN' },
  TO: { name: '통가', flag: 'TO' },
  TR: { name: '튀르키예', flag: 'TR' },
  TT: { name: '트리니다드 토바고', flag: 'TT' },
  TV: { name: '투발루', flag: 'TV' },
  TW: { name: '대만', flag: 'TW' },
  TZ: { name: '탄자니아', flag: 'TZ' },
  UA: { name: '우크라이나', flag: 'UA' },
  UG: { name: '우간다', flag: 'UG' },
  UM: { name: '미국령 군소 제도', flag: 'UM' },
  US: { name: '미국', flag: 'US' },
  UY: { name: '우루과이', flag: 'UY' },
  UZ: { name: '우즈베키스탄', flag: 'UZ' },
  VA: { name: '바티칸 시국', flag: 'VA' },
  VC: { name: '세인트빈센트 그레나딘', flag: 'VC' },
  VE: { name: '베네수엘라', flag: 'VE' },
  VG: { name: '영국령 버진아일랜드', flag: 'VG' },
  VI: { name: '미국령 버진아일랜드', flag: 'VI' },
  VN: { name: '베트남', flag: 'VN' },
  VU: { name: '바누아투', flag: 'VU' },
  WF: { name: '왈리스 푸투나', flag: 'WF' },
  WS: { name: '사모아', flag: 'WS' },
  YE: { name: '예멘', flag: 'YE' },
  YT: { name: '마요트', flag: 'YT' },
  ZA: { name: '남아프리카 공화국', flag: 'ZA' },
  ZM: { name: '잠비아', flag: 'ZM' },
  ZW: { name: '짐바브웨', flag: 'ZW' },
} as const;
