export const COUNTRY_CODE = {
  ADZ: { name: '안도라', flag: 'None' },
  AEZ: { name: '아랍에미리트', flag: 'None' },
  AFZ: { name: '아프가니스탄', flag: 'None' },
  AGZ: { name: '앤티가 바부다', flag: 'None' },
  AIZ: { name: '앵귈라', flag: 'None' },
  ALZ: { name: '알바니아', flag: 'None' },
  AMZ: { name: '아르메니아', flag: 'None' },
  AOZ: { name: '앙골라', flag: 'None' },
  AQZ: { name: '남극', flag: 'None' },
  ARZ: { name: '아르헨티나', flag: 'None' },
  ASZ: { name: '아메리칸사모아', flag: 'None' },
  ATZ: { name: '오스트리아', flag: 'None' },
  AUZ: { name: '오스트레일리아', flag: 'None' },
  AWZ: { name: '아루바', flag: 'None' },
  AXZ: { name: '올란드 제도', flag: 'None' },
  AZZ: { name: '아제르바이잔', flag: 'None' },
  BAZ: { name: '보스니아 헤르체고비나', flag: 'None' },
  BBZ: { name: '바베이도스', flag: 'None' },
  BDZ: { name: '방글라데시', flag: 'None' },
  BEZ: { name: '벨기에', flag: 'None' },
  BFZ: { name: '부르키나파소', flag: 'None' },
  BGZ: { name: '불가리아', flag: 'None' },
  BHZ: { name: '바레인', flag: 'None' },
  BIZ: { name: '부룬디', flag: 'None' },
  BJZ: { name: '베냉', flag: 'None' },
  BLZ: { name: '생바르텔레미', flag: 'None' },
  BMZ: { name: '버뮤다', flag: 'None' },
  BNZ: { name: '브루나이', flag: 'None' },
  BOZ: { name: '볼리비아', flag: 'None' },
  BQZ: { name: '보네르섬', flag: 'None' },
  BRZ: { name: '브라질', flag: 'None' },
  BSZ: { name: '바하마', flag: 'None' },
  BTZ: { name: '부탄', flag: 'None' },
  BVZ: { name: '부베섬', flag: 'None' },
  BWZ: { name: '보츠와나', flag: 'None' },
  BYZ: { name: '벨라루스', flag: 'None' },
  BZZ: { name: '벨리즈', flag: 'None' },
  CAZ: { name: '캐나다', flag: 'None' },
  CCZ: { name: '코코스 제도', flag: 'None' },
  CDZ: { name: '콩고 민주 공화국', flag: 'None' },
  CFZ: { name: '중앙아프리카 공화국', flag: 'None' },
  CGZ: { name: '콩고 공화국', flag: 'None' },
  CHZ: { name: '스위스', flag: 'None' },
  CIZ: { name: '코트디부아르', flag: 'None' },
  CKZ: { name: '쿡 제도', flag: 'None' },
  CLZ: { name: '칠레', flag: 'None' },
  CMZ: { name: '카메룬', flag: 'None' },
  CNZ: { name: '중국', flag: 'CNZ' },
  COZ: { name: '콜롬비아', flag: 'None' },
  CRZ: { name: '코스타리카', flag: 'None' },
  CUZ: { name: '쿠바', flag: 'None' },
  CVZ: { name: '카보베르데', flag: 'None' },
  CWZ: { name: '퀴라소', flag: 'None' },
  CXZ: { name: '크리스마스섬', flag: 'None' },
  CYZ: { name: '키프로스', flag: 'None' },
  CZZ: { name: '체코', flag: 'None' },
  DEZ: { name: '독일', flag: 'None' },
  DJZ: { name: '지부티', flag: 'None' },
  DKZ: { name: '덴마크', flag: 'None' },
  DMZ: { name: '도미니카 연방', flag: 'None' },
  DOZ: { name: '도미니카 공화국', flag: 'None' },
  DZZ: { name: '알제리', flag: 'None' },
  ECZ: { name: '에콰도르', flag: 'None' },
  EEZ: { name: '에스토니아', flag: 'None' },
  EGZ: { name: '이집트', flag: 'None' },
  EHZ: { name: '서사하라', flag: 'None' },
  ERZ: { name: '에리트레아', flag: 'None' },
  ESZ: { name: '스페인', flag: 'None' },
  ETZ: { name: '에티오피아', flag: 'None' },
  FIZ: { name: '핀란드', flag: 'None' },
  FJZ: { name: '피지', flag: 'None' },
  FKZ: { name: '포클랜드 제도', flag: 'None' },
  FMZ: { name: '미크로네시아 연방', flag: 'None' },
  FOZ: { name: '페로 제도', flag: 'None' },
  FRZ: { name: '프랑스', flag: 'None' },
  GAZ: { name: '가봉', flag: 'None' },
  GBZ: { name: '영국', flag: 'None' },
  GDZ: { name: '그레나다', flag: 'None' },
  GEZ: { name: '조지아', flag: 'None' },
  GFZ: { name: '프랑스령 기아나', flag: 'None' },
  GGZ: { name: '건지섬', flag: 'None' },
  GHZ: { name: '가나', flag: 'None' },
  GIZ: { name: '지브롤터', flag: 'None' },
  GLZ: { name: '그린란드', flag: 'None' },
  GMZ: { name: '감비아', flag: 'None' },
  GNZ: { name: '기니', flag: 'None' },
  GPZ: { name: '과들루프', flag: 'None' },
  GQZ: { name: '적도 기니', flag: 'None' },
  GRZ: { name: '그리스', flag: 'None' },
  GSZ: { name: '사우스조지아 사우스샌드위치 제도', flag: 'None' },
  GTZ: { name: '과테말라', flag: 'None' },
  GUZ: { name: '괌', flag: 'None' },
  GWZ: { name: '기니비사우', flag: 'None' },
  GYZ: { name: '가이아나', flag: 'None' },
  HKZ: { name: '홍콩', flag: 'None' },
  HMZ: { name: '허드 맥도널드 제도', flag: 'None' },
  HNZ: { name: '온두라스', flag: 'None' },
  HRZ: { name: '크로아티아', flag: 'None' },
  HTZ: { name: '아이티', flag: 'None' },
  HUZ: { name: '헝가리', flag: 'None' },
  IDZ: { name: '인도네시아', flag: 'None' },
  IEZ: { name: '아일랜드', flag: 'None' },
  ILZ: { name: '이스라엘', flag: 'None' },
  IMZ: { name: '맨섬', flag: 'None' },
  INZ: { name: '인도', flag: 'None' },
  IOZ: { name: '영국령 인도양 지역', flag: 'None' },
  IQZ: { name: '이라크', flag: 'None' },
  IRZ: { name: '이란', flag: 'None' },
  ISZ: { name: '아이슬란드', flag: 'None' },
  ITZ: { name: '이탈리아', flag: 'None' },
  JEZ: { name: '저지섬', flag: 'None' },
  JMZ: { name: '자메이카', flag: 'None' },
  JOZ: { name: '요르단', flag: 'None' },
  JPZ: { name: '일본', flag: 'None' },
  KEZ: { name: '케냐', flag: 'None' },
  KGZ: { name: '키르기스스탄', flag: 'None' },
  KHZ: { name: '캄보디아', flag: 'None' },
  KIZ: { name: '키리바시', flag: 'None' },
  KMZ: { name: '코모로', flag: 'None' },
  KNZ: { name: '세인트키츠 네비스', flag: 'None' },
  KPZ: { name: '조선민주주의인민공화국', flag: 'None' },
  KRZ: { name: '대한민국', flag: 'KRZ' },
  KWZ: { name: '쿠웨이트', flag: 'None' },
  KYZ: { name: '케이맨 제도', flag: 'None' },
  KZZ: { name: '카자흐스탄', flag: 'None' },
  LAZ: { name: '라오스', flag: 'None' },
  LBZ: { name: '레바논', flag: 'None' },
  LCZ: { name: '세인트루시아', flag: 'None' },
  LKZ: { name: '스리랑카', flag: 'None' },
  LIZ: { name: '리히텐슈타인', flag: 'None' },
  LRZ: { name: '라이베리아', flag: 'None' },
  LSZ: { name: '레소토', flag: 'None' },
  LTZ: { name: '리투아니아', flag: 'None' },
  LUZ: { name: '룩셈부르크', flag: 'None' },
  LVZ: { name: '라트비아', flag: 'None' },
  LYZ: { name: '리비아', flag: 'None' },
  MAZ: { name: '모로코', flag: 'None' },
  MCZ: { name: '모나코', flag: 'None' },
  MDZ: { name: '몰도바', flag: 'None' },
  MEZ: { name: '몬테네그로', flag: 'None' },
  MFZ: { name: '생마르탱', flag: 'None' },
  MGZ: { name: '마다가스카르', flag: 'None' },
  MHZ: { name: '마셜 제도', flag: 'None' },
  MKZ: { name: '북마케도니아', flag: 'None' },
  MLZ: { name: '말리', flag: 'None' },
  MMZ: { name: '미얀마', flag: 'None' },
  MNZ: { name: '몽골', flag: 'None' },
  MOZ: { name: '마카오', flag: 'None' },
  MPZ: { name: '북마리아나 제도', flag: 'None' },
  MQZ: { name: '마르티니크', flag: 'None' },
  MRZ: { name: '모리타니', flag: 'None' },
  MSZ: { name: '몬트세랫', flag: 'None' },
  MTZ: { name: '몰타', flag: 'None' },
  MUZ: { name: '모리셔스', flag: 'None' },
  MVZ: { name: '몰디브', flag: 'None' },
  MWZ: { name: '말라위', flag: 'None' },
  MXZ: { name: '멕시코', flag: 'None' },
  MYZ: { name: '말레이시아', flag: 'MYZ' },
  MZZ: { name: '모잠비크', flag: 'None' },
  NAZ: { name: '나미비아', flag: 'None' },
  NCZ: { name: '누벨칼레도니', flag: 'None' },
  NEZ: { name: '니제르', flag: 'None' },
  NFZ: { name: '노퍽섬', flag: 'None' },
  NGZ: { name: '나이지리아', flag: 'None' },
  NIZ: { name: '니카라과', flag: 'None' },
  NLZ: { name: '네덜란드', flag: 'None' },
  NOZ: { name: '노르웨이', flag: 'None' },
  NPZ: { name: '네팔', flag: 'None' },
  NRZ: { name: '나우루', flag: 'None' },
  NUZ: { name: '니우에', flag: 'None' },
  NZZ: { name: '뉴질랜드', flag: 'None' },
  OMZ: { name: '오만', flag: 'None' },
  PAZ: { name: '파나마', flag: 'None' },
  PEZ: { name: '페루', flag: 'None' },
  PFZ: { name: '프랑스령 폴리네시아', flag: 'None' },
  PGZ: { name: '파푸아뉴기니', flag: 'None' },
  PHZ: { name: '필리핀', flag: 'None' },
  PKZ: { name: '파키스탄', flag: 'None' },
  PLZ: { name: '폴란드', flag: 'None' },
  PMZ: { name: '생피에르 미클롱', flag: 'None' },
  PNZ: { name: '핏케언 제도', flag: 'None' },
  PRZ: { name: '푸에르토리코', flag: 'None' },
  PSZ: { name: '팔레스타인', flag: 'None' },
  PTZ: { name: '포르투갈', flag: 'None' },
  PWZ: { name: '팔라우', flag: 'None' },
  PYZ: { name: '파라과이', flag: 'None' },
  QAZ: { name: '카타르', flag: 'None' },
  REZ: { name: '레위니옹', flag: 'None' },
  ROZ: { name: '루마니아', flag: 'None' },
  RSZ: { name: '세르비아', flag: 'None' },
  RUZ: { name: '러시아', flag: 'None' },
  RWZ: { name: '르완다', flag: 'None' },
  SAZ: { name: '사우디아라비아', flag: 'None' },
  SBZ: { name: '솔로몬 제도', flag: 'None' },
  SCZ: { name: '세이셸', flag: 'None' },
  SDZ: { name: '수단', flag: 'None' },
  SEZ: { name: '스웨덴', flag: 'None' },
  SGZ: { name: '싱가포르', flag: 'None' },
  SHZ: { name: '세인트헬레나', flag: 'None' },
  SIZ: { name: '슬로베니아', flag: 'None' },
  SJZ: { name: '스발바르 얀마옌', flag: 'None' },
  SKZ: { name: '슬로바키아', flag: 'None' },
  SLZ: { name: '시에라리온', flag: 'None' },
  SMZ: { name: '산마리노', flag: 'None' },
  SNZ: { name: '세네갈', flag: 'None' },
  SOZ: { name: '소말리아', flag: 'None' },
  SRZ: { name: '수리남', flag: 'None' },
  SSZ: { name: '남수단', flag: 'None' },
  STZ: { name: '상투메 프린시페', flag: 'None' },
  SVZ: { name: '엘살바도르', flag: 'None' },
  SXZ: { name: '신트마르턴', flag: 'None' },
  SYZ: { name: '시리아', flag: 'None' },
  SZZ: { name: '에스와티니', flag: 'None' },
  TCZ: { name: '터크스 케이커스 제도', flag: 'None' },
  TDZ: { name: '차드', flag: 'None' },
  TFZ: { name: '프랑스령 남방 및 남극 지역', flag: 'None' },
  TGZ: { name: '토고', flag: 'None' },
  THZ: { name: '태국', flag: 'None' },
  TJZ: { name: '타지키스탄', flag: 'None' },
  TKZ: { name: '토켈라우', flag: 'None' },
  TLZ: { name: '동티모르', flag: 'None' },
  TMZ: { name: '투르크메니스탄', flag: 'None' },
  TNZ: { name: '튀니지', flag: 'None' },
  TOZ: { name: '통가', flag: 'None' },
  TRZ: { name: '튀르키예', flag: 'None' },
  TTZ: { name: '트리니다드 토바고', flag: 'None' },
  TVZ: { name: '투발루', flag: 'None' },
  TWZ: { name: '중화민국', flag: 'None' },
  TZZ: { name: '탄자니아', flag: 'None' },
  UAZ: { name: '우크라이나', flag: 'None' },
  UGZ: { name: '우간다', flag: 'None' },
  UMZ: { name: '미국령 군소 제도', flag: 'None' },
  USZ: { name: '미국', flag: 'None' },
  UYZ: { name: '우루과이', flag: 'None' },
  UZZ: { name: '우즈베키스탄', flag: 'None' },
  VAZ: { name: '바티칸 시국', flag: 'None' },
  VCZ: { name: '세인트빈센트 그레나딘', flag: 'None' },
  VEZ: { name: '베네수엘라', flag: 'None' },
  VGZ: { name: '영국령 버진아일랜드', flag: 'None' },
  VIZ: { name: '미국령 버진아일랜드', flag: 'None' },
  VNZ: { name: '베트남', flag: 'None' },
  VUZ: { name: '바누아투', flag: 'None' },
  WFZ: { name: '왈리스 푸투나', flag: 'None' },
  WSZ: { name: '사모아', flag: 'None' },
  YEZ: { name: '예멘', flag: 'None' },
  YTZ: { name: '마요트', flag: 'None' },
  ZAZ: { name: '남아프리카 공화국', flag: 'None' },
  ZMZ: { name: '잠비아', flag: 'None' },
  ZWZ: { name: '짐바브웨', flag: 'None' },
} as const;
