name: cd for dev

concurrency:
  group: cd-for-dev
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout source code
        uses: actions/checkout@master

      - name: Install & build for client
        run: yarn user:dev-build

      - name: Install & build for office
        run: yarn office:dev-build

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run scripts in server
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.AWS_KEY }}
          host: ${{ secrets.AWS_DEV_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          script: |
            ./dev-client-deploy.sh